const common = {
  app: {
    title: 'Statistical Traps',
    subtitle: 'Finding Patterns in Data',
    skipToContent: 'Skip to content',
  },
  language: {
    label: 'Language',
    cs: 'Čeština',
    en: 'English',
  },
  nav: {
    overview: 'Overview',
    backToOverview: 'Back to overview',
  },
  status: {
    available: 'Available',
    planned: 'Planned',
  },
  actions: {
    open: 'Open scenario',
    next: 'Continue',
    previous: 'Back',
    restart: 'Start again',
  },
  home: {
    heading: 'How easily can we find a pattern that is not there?',
    lead: 'An interactive simulation about the difference between discovering a pattern and showing that the pattern is real.',
    body1:
      'In every scenario the data are generated by us, so the truth is known in advance: there is no effect to find. Then we go looking for one anyway — by moving a target, choosing a model, picking a subgroup, or testing many outcomes at once. Something interesting always turns up.',
    body2:
      'The decisive step is what comes next. A pattern found by searching is a hypothesis, not a result. It has to be tested on data that were not used to find it.',
    cycleHeading: 'The recurring pattern',
    cycle: {
      data: 'Data',
      search: 'Search for an interesting pattern',
      result: 'Apparently convincing result',
      validate: 'Test on new, independent data',
      outcome: 'The pattern weakens or disappears',
    },
    disclaimerHeading: 'This is not an argument against statistics',
    disclaimerBody:
      'Statistics, data mining and machine learning are not the problem, and searching data for patterns is a normal part of research. The problem is confusing pattern discovery with hypothesis confirmation — reporting a hypothesis that came out of the data as if it had been specified before the data.',
    scenariosHeading: 'Scenarios',
    scenariosLead:
      'Each scenario is self-contained. They are built in order, and the later ones apply the same idea to situations that feel less like a game.',
  },
  scenario: {
    stepOf: 'Step {{current}} of {{total}}',
    conceptsHeading: 'Concepts',
    trueProcessHeading: 'True data-generating process',
    planned: {
      heading: 'Not implemented yet',
      body: 'This scenario is part of the planned sequence, but it has not been built yet. Scenarios are implemented one at a time, so that each one can be tested and documented before the next begins.',
    },
    notFound: {
      heading: 'Scenario not found',
      body: 'No scenario with this address exists.',
    },
  },
  stages: {
    introduction: 'Introduction',
    experiment: 'Experiment',
    observation: 'Observation',
    analysis: 'Analysis',
    validation: 'Validation',
    conclusion: 'Conclusion',
  },
  explanation: {
    show: 'Why does this happen?',
    hide: 'Hide the explanation',
  },
  concepts: {
    postHocHypothesis: 'post-hoc hypothesis',
    exploratoryAnalysis: 'exploratory analysis',
    confirmation: 'confirmation',
    replication: 'replication',
    overfitting: 'overfitting',
    modelSelection: 'model selection',
    trainingData: 'training data',
    testData: 'test data',
    generalization: 'generalization',
    multipleComparisons: 'multiple comparisons',
    researcherDegreesOfFreedom: 'researcher degrees of freedom',
    falseDiscoveries: 'false discoveries',
    selection: 'selection after seeing the data',
    extremeValues: 'extreme values',
    confounding: 'confounding',
    riskAdjustment: 'risk adjustment',
    investigationVersusProof: 'investigation versus proof',
    multipleTesting: 'multiple testing',
    falsePositives: 'false positives',
    independentReplication: 'independent replication',
    pValueInterpretation: 'interpretation of p-values',
    dataMining: 'data mining',
    correlation: 'correlation',
    predictionVersusExplanation: 'prediction versus explanation',
    patternDiscovery: 'pattern discovery',
    hypothesisGeneration: 'hypothesis generation',
    causalInference: 'causal inference',
  },
  scenarios: {
    '01-dartboard': {
      title: 'Drawing the Target Around the Darts',
      summary:
        'Darts land completely at random. Move the target after the throw and the result looks convincing — until the machine throws again.',
    },
    '02-best-line': {
      title: 'Find the Best Line',
      summary:
        'Two-dimensional observations with no real relationship. A flexible enough model describes them beautifully, and new data badly.',
    },
    '03-interesting-region': {
      title: 'Find the Interesting Region',
      summary:
        'A record with no trend in it anywhere. Search enough stretches of it and one of them will look like something happened.',
    },
    '04-doctor-mortality': {
      title: 'The Doctor With Unusually High Mortality',
      summary:
        'A simulated hospital where no doctor is better or worse than any other. Their patients differ, and one doctor still ends up with a strikingly high number of deaths.',
    },
    '05-miracle-drug': {
      title: 'The Miracle Drug',
      summary:
        'A simulated trial of a treatment with no effect at all, measured on many outcomes. One of them comes out significant.',
    },
    '06-mysterious-correlation': {
      title: 'The Mysterious Correlation',
      summary:
        'An automated analyst searches many variables for relationships and finds a strong one. Fresh data decide what it was worth.',
    },
    '07-ai-synthesis': {
      title: 'What Does This Mean for AI?',
      summary:
        'A synthesis: pattern discovery, prediction, hypothesis generation, testing, causal inference and generalization are different things.',
    },
  },
  footer: {
    note: 'Every data set in this application is simulated. No real people, hospitals, patients or studies are involved.',
    source: 'Educational project',
  },
}

export default common
