const miracledrug = {
  intro: {
    heading: 'One outcome, registered before anyone is enrolled',
    body1:
      'A simulated trial. Patients are split into two arms, one given the treatment and one not, and every patient is measured on a whole panel of outcomes at the end. The measurements are not independent of each other: a patient who is doing well tends to score well on several of them at once, exactly as measurements on the same person do.',
    body2:
      'The treatment does nothing. Both arms are drawn from the same distribution, and no term anywhere depends on which arm a patient is in, so the true effect on every outcome in the panel is exactly zero.',
    goalHeading: 'What this experiment is meant to show',
    goalBody:
      'That a test at the 5% level is meant to be wrong about one time in twenty — so if you measure {{outcomes}} outcomes on a treatment that does nothing and report the best one, you get a "finding" purely because you measured {{outcomes}} things. And that the report of that finding gives no sign of it.',
    goalStep1:
      'Run the trial and test the outcome we registered in advance. It finds nothing.',
    goalStep2:
      'Then look at all the others and pick the one that came out best. That one looks like a finding.',
    goalStep3:
      'Then correct it twice over, and run the whole trial again on new patients. Nothing of it survives.',
    question:
      'On outcome {{outcome}}, the one this trial is registered on, does the treated arm differ from the untreated arm by more than chance allows?',
    body3:
      'That outcome is registered now, before anybody is enrolled, so nothing about the results can have influenced the choice. Everything that follows comes from the other outcomes — the ones we also happened to measure.',
    trueProcess:
      'Each patient gets a shared score, and each outcome is that shared score plus its own independent noise. Both arms are generated by the identical process. True effect of the treatment on every outcome: zero.',
    fictionHeading: 'Nothing here is real',
    fictionBody:
      'The trial, the patients and the measurements are generated in your browser from a seed. No real treatment, condition, study or patient is involved, and no empirical clinical statistic is used or implied. The outcomes are numbered rather than named on purpose: a named outcome invites a story, and a story is what makes a selected result persuasive.',
    action: 'Run the trial',
  },
  experiment: {
    heading: 'The results are in',
    body1:
      'Each row is one outcome. The dot is the difference between the treated and untreated arms; the bar around it shows how imprecisely that difference is measured — with {{perArm}} patients an arm, the imprecision is large. The vertical line is zero, meaning no difference at all.',
    body2:
      'The registered outcome is marked. Its interval comfortably contains zero and the test on it finds nothing. That is as it should be, because there is nothing to find.',
    body2Hit:
      'The registered outcome is marked, and this time its p-value came out below 0.05. It is a false alarm: about one trial in twenty ends up like this even when the treatment does nothing at all. This is the twentieth. Run the trial with a different seed and the outcome drops back to nothing.',
    numbersTitle: 'What do these numbers mean?',
    numbersBody1:
      'A p-value answers one question: if the treatment did nothing, how often would this outcome show a difference at least this large anyway? 0.765 means "a difference like this turns up in three quarters of trials by chance alone". 0.004 means "a difference like this turns up by chance in about four trials in a thousand" — which is where numbers start being called findings. The 0.05 threshold is a convention, not a proof.',
    numbersBody2:
      'The letter t is that same difference expressed as a multiple of its own imprecision: a t near zero is a difference drowned in noise, a t near three is one that stands out of it. The p-value is computed from it, so the two numbers say the same thing twice.',
    action: 'Now look at the others',
  },
  controls: {
    heading: 'Experiment settings',
    patientsPerArm: 'Patients per arm',
    outcomeCount: 'Outcomes measured',
    seed: 'Seed',
    newSeed: 'New seed',
    hint: 'The same seed always produces the same trial, so any result here can be reproduced exactly. Measuring more outcomes does not make the treatment work — it makes a striking outcome more likely.',
  },
  plot: {
    notStarted: 'The trial has not been run yet.',
    aria: 'Difference between the arms on each of {{count}} outcomes, with confidence intervals.',
    outcomeAria: 'Outcome {{outcome}}, difference {{difference}}. Select to inspect.',
    legendOutcome: 'One outcome',
    legendInterval: 'Dot: difference · bar: how imprecise it is',
  },
  outcomes: {
    primary: 'Outcome {{outcome}}, registered in advance',
    primaryShort: 'Registered in advance',
    chosen: 'Outcome {{outcome}}, picked out of the panel',
    chosenShort: 'Picked out afterwards',
  },
  stats: {
    outcomes: 'Outcomes',
    patients: 'Patients',
    patientsHint: '{{perArm}} in each arm',
    significantCount: 'Below 0.05',
    significantHint: 'of {{outcomes}} outcomes, each tested on its own',
    difference: 'Difference',
    differenceHint: 'Treated arm minus untreated arm.',
    t: 't',
    pValue: 'p-value as usually reported',
  },
  observation: {
    heading: 'Find the outcome that worked',
    body1:
      'The whole panel is in front of you. Click any row to inspect that outcome: the difference between the arms, and the p-value that difference would normally be reported with.',
    clickHint:
      'Every outcome is tested exactly as the registered one was — the same two-sample test, the same patients, the same trial. The only thing that changes is which result we decided to talk about.',
    body2:
      '{{count}} of the {{outcomes}} outcomes came out below 0.05 on their own. For a treatment that does nothing, that is no surprise: at the 5% level every twentieth test is wrong, so out of {{outcomes}} about {{expected}} go wrong on average. How often a trial ends up with at least one finding is something we are about to measure.',
    autoBest: 'Show me the outcome that worked',
    reset: 'Clear the selection',
    autoBestNote:
      'That is the most impressive of the {{outcomes}} outcomes, found by testing every one of them and keeping the smallest p-value. Reported on its own, nothing about it would look like a search.',
    selectFirst: 'Choose an outcome to take further.',
    action: 'Write it up properly',
  },
  analysis: {
    heading: 'The same test, two ways of choosing an outcome',
    body1:
      'Both rows below were tested identically: the same two-sample test on the same patients from the same trial. The only difference is whether the outcome was named before the trial or picked out of its results afterwards.',
    naivePValue: 'p-value as usually reported',
    naiveHint: 'The test compares the treated and untreated arms, on this one outcome alone.',
    verdictNothing: 'Nothing to report',
    verdictStriking: 'Looks like a finding',
    runFirst:
      'Both corrections below are the point of this stage: without them, the row above is the number that would be reported.',
    textbook: {
      heading: 'Correction 1: the textbook one',
      body: 'The standard answer to testing {{outcomes}} things at once: make each one clear a higher bar, so that the chance of any false positive across the whole panel stays at 5%.',
      bonferroni: 'Bonferroni',
      bonferroniHint: 'The p-value multiplied by {{outcomes}}.',
      holm: 'Holm',
      holmHint: 'A step-down version: never more severe than Bonferroni, often less.',
      note: 'Multiplying by the number of tests is the right instinct and a crude instrument. It assumes every outcome was a separate chance. Measurements on the same patients are not separate.',
    },
    selection: {
      heading: 'Correction 2: simulate what was actually done',
      body: 'Rather than assume how many chances the search had, we simulate it: run another trial of a treatment that does nothing, test all {{outcomes}} outcomes, and keep the smallest p-value. Repeat {{replications}} times.',
      run: 'Simulate the search {{replications}} times',
      running: 'Simulating…',
      histogramTitle: 'Smallest p-value in the panel, trial after trial, with no effect anywhere',
      histogramX: 'Smallest p-value in the trial',
      histogramY: 'Number of simulated trials',
      marker: 'Your outcome',
      adjusted: 'p-value adjusted for the search',
      adjustedHint:
        'Simulated p-value: how often a trial of a treatment that does nothing produces a best outcome at least as impressive as {{pValue}}.',
      shareSignificant:
        'In {{share}} of the simulated trials at least one outcome came out below 0.05, and on average {{average}} of the {{outcomes}} did — in trials where the treatment does nothing whatsoever.',
      versusBonferroni:
        'Compare the two corrections: the simulated one gives p {{simulated}}, Bonferroni p {{bonferroni}}. Bonferroni charges for {{outcomes}} independent chances, but these outcomes correlate at about {{correlation}}. The search had fewer genuinely separate chances than that, and simulating the actual procedure prices it correctly.',
      conclusion:
        'The same result read two ways: p {{naive}} for an outcome registered in advance, p {{adjusted}} for an outcome found by looking. The patients are the same patients.',
      gallery: {
        heading: 'The five most impressive results those simulations produced',
        body: 'Every trial below is a trial of a treatment that does nothing at all. In each one, the marked row is the outcome that happened to come out best, and each would have been perfectly publishable on its own.',
        caption: 'Simulated trial {{index}}',
        item: 'Outcome {{outcome}} · difference {{difference}}',
        itemStats: 'p {{p}}',
        plotAria:
          'Simulated trial {{index}}: a treatment that does nothing, with outcome {{outcome}} marked as the best result of that trial.',
      },
    },
    explanation: {
      title: 'Why does this happen?',
      body1:
        'A test at the 5% level is wrong about one time in twenty, by design — that is what the 5% means. Run twenty of them on a treatment that does nothing and being wrong about once is not bad luck, it is the expected outcome. The panel does not have to be large for this: even five or six outcomes make a striking result more likely than not over a few trials.',
      body2:
        'What makes it hard to see is that the report does not show the panel. A single outcome, with its p-value and its confidence interval, looks exactly the same whether it was the only thing measured or the best of twenty. Nothing in the number records which it was, and nothing in the arithmetic can recover it.',
      body3:
        'This is the same mistake as drawing the target around the darts, choosing the model that fits best, marking the most striking period, and picking the worst doctor from a table. Here the search runs over outcomes, and the report arrives with a p-value, an interval and a mechanism — which is why this version of it is the one that gets published.',
    },
    action: 'Run the trial again',
  },
  validation: {
    heading: 'A new trial, new patients',
    body1:
      'Both outcomes are now fixed in advance of the trial being run — one by the original registration, one by the first trial’s results. New patients are enrolled, and both outcomes are measured again.',
    body2:
      'The registered outcome behaves as it did before. So does the one that worked, and that is the point: on patients who took no part in choosing it, it is an ordinary row in an ordinary panel.',
    firstTrial: 'First trial',
    nextDifference: 'New trial: difference',
    nextPValue: 'New trial: p-value',
    tableHint: 'The same two outcomes, measured on patients who took no part in choosing either of them.',
    freshTrial: 'A new trial',
    drawFresh: 'Run another independent trial',
    replications: {
      heading: 'Repeat the trial many times',
      body: 'Each replication is another independent trial of the same design, measured on the same two frozen outcomes.',
      run: 'Run {{replications}} trials',
      meanDifference: 'Average difference',
      shareSignificant: 'Significant in a trial',
      sameDirection: 'Same direction again',
      tableHint:
        'Both outcomes were fixed before these trials existed, so both should be significant about 5% of the time — and both are. An average difference near zero is what a treatment with no effect looks like.',
      note: 'Search each new trial again and it lands on a different outcome {{share}} of the time. Every trial of this treatment produces a best outcome, and it is almost never the same one. That is what a finding looks like when it belongs to the data rather than to the world.',
    },
    action: 'What should we take away?',
  },
  conclusion: {
    heading: 'What this scenario shows',
    point1:
      'A p-value describes one test specified in advance. Measure more of them and report the best, and it describes the last step of a search instead.',
    point2:
      'The panel is part of the result, and the report is where it disappears. A selected outcome looks identical to a registered one on the page.',
    point3:
      'Correcting for the search is not optional arithmetic, and multiplying by the number of tests is only a rough version of it. Simulating what was actually done prices the search properly.',
    point4:
      'A replication trial settles it. A treatment that works keeps working on new patients; a selected outcome does not, and moves somewhere else each time.',
    legitimate: {
      heading: 'Measuring many outcomes is not the error',
      body: 'Trials measure many things for good reasons: safety, side effects, quality of life, and genuine exploration that generates the next hypothesis. That is why registration exists — the primary outcome and the analysis are stated before the data, and everything else is reported as what it is, exploratory. The error is promoting an exploratory outcome to the headline afterwards and not mentioning the rest.',
    },
    nextHeading: 'Where this goes next',
    nextBody:
      'The searches so far have run over positions, models, periods, people and outcomes, always by hand and always over one panel at a time. The next scenario hands the search to an algorithm that can try thousands of variable pairs a second — which changes the scale of the problem and nothing else about it.',
  },
}

export default miracledrug
